/**
 * Video Service
 *
 * This service handles video consultation operations including:
 * - Fetching Google Meet links for online appointments
 * - Opening video consultation links in new tabs
 *
 * Video consultations are available for appointments with type "ONLINE".
 * The backend generates Google Meet links for these appointments, and this
 * service provides methods to retrieve and access those links.
 *
 * @module services/videoService
 */

import apiClient from "./api";
import type { VideoLink, APIResponse } from "../types";

/**
 * Video Service Class
 *
 * Manages video consultation link operations.
 * Implements singleton pattern - use the exported instance.
 */
class VideoService {
  /**
   * Get video consultation link for an appointment
   *
   * Fetches the Google Meet link associated with an online appointment.
   * The link is generated by the backend when an online appointment is
   * created or confirmed.
   *
   * Requirements:
   * - Appointment must be of type "ONLINE"
   * - Appointment must be in CONFIRMED or BOOKED status
   * - Video link must have been generated by the backend
   *
   * @param appointmentId - ID of the appointment
   * @returns Promise with video link details
   * @throws {AxiosError} If appointment not found, not online, or link not available
   *
   * @example
   * ```typescript
   * try {
   *   const videoLink = await videoService.getVideoLink(456);
   *   console.log(`Meet Link: ${videoLink.meet_link}`);
   *   console.log(`Provider: ${videoLink.provider}`);
   *   console.log(`Created: ${new Date(videoLink.created_at).toLocaleString()}`);
   *
   *   // Open the link
   *   videoService.openVideoLink(videoLink.meet_link);
   * } catch (error) {
   *   if (error.response?.status === 404) {
   *     console.error("Video link not available for this appointment");
   *   } else {
   *     console.error("Failed to fetch video link:", error);
   *   }
   * }
   * ```
   */
  async getVideoLink(appointmentId: number): Promise<VideoLink> {
    try {
      const response = await apiClient.get<APIResponse<VideoLink>>(
        `/video/appointment/${appointmentId}/meet-link`
      );

      console.log(
        `Video link fetched for appointment ${appointmentId}:`,
        response.data.data.meet_link
      );
      return response.data.data;
    } catch (error) {
      console.error(
        `Failed to fetch video link for appointment ${appointmentId}:`,
        error
      );
      throw error;
    }
  }

  /**
   * Open video consultation link in new tab
   *
   * Opens a Google Meet link in a new browser tab with security features:
   * - Opens in new tab (not new window)
   * - Prevents opener access (noopener)
   * - Prevents referrer leakage (noreferrer)
   *
   * This method should be called when the patient clicks "Join Video Call"
   * button on an online appointment.
   *
   * @param meetLink - Google Meet URL
   *
   * @example
   * ```typescript
   * // In appointment card component
   * const handleJoinCall = async () => {
   *   try {
   *     const videoLink = await videoService.getVideoLink(appointmentId);
   *     videoService.openVideoLink(videoLink.meet_link);
   *   } catch (error) {
   *     toast.error("Unable to join video call. Please try again.");
   *   }
   * };
   * ```
   */
  openVideoLink(meetLink: string): void {
    // Validate that the link is a valid URL
    try {
      new URL(meetLink);
    } catch (error) {
      console.error("Invalid video link URL:", meetLink);
      throw new Error("Invalid video link URL");
    }

    // Open link in new tab with security features
    const newWindow = window.open(meetLink, "_blank", "noopener,noreferrer");

    // Check if popup was blocked
    if (
      !newWindow ||
      newWindow.closed ||
      typeof newWindow.closed === "undefined"
    ) {
      console.warn("Popup blocked - video link could not be opened");
      throw new Error(
        "Unable to open video link. Please allow popups for this site."
      );
    }

    console.log("Video link opened in new tab");
  }

  /**
   * Check if appointment is eligible for video consultation
   *
   * Determines if a video call button should be shown for an appointment.
   * Checks:
   * - Appointment type is ONLINE
   * - Appointment status is CONFIRMED or BOOKED
   * - Appointment time is within 15 minutes of start time
   *
   * @param appointment - Appointment object
   * @returns true if video call is available, false otherwise
   *
   * @example
   * ```typescript
   * import appointmentService from './appointmentService';
   * import videoService from './videoService';
   *
   * const appointment = await appointmentService.getAppointmentById(456);
   *
   * if (videoService.isVideoCallAvailable(appointment)) {
   *   // Show "Join Video Call" button
   * } else {
   *   // Hide button or show "Not available yet" message
   * }
   * ```
   */
  isVideoCallAvailable(appointment: {
    appointment_type: string;
    status: string;
    scheduled_start_at: string;
  }): boolean {
    // Check if appointment is online
    if (appointment.appointment_type !== "ONLINE") {
      return false;
    }

    // Check if appointment is in valid status
    const validStatuses = ["CONFIRMED", "BOOKED"];
    if (!validStatuses.includes(appointment.status)) {
      return false;
    }

    // Check if appointment is within 15 minutes of start time
    const startTime = new Date(appointment.scheduled_start_at);
    const now = new Date();
    const fifteenMinutes = 15 * 60 * 1000; // 15 minutes in milliseconds

    // Allow joining 15 minutes before start time
    const canJoin = startTime.getTime() - now.getTime() <= fifteenMinutes;

    return canJoin;
  }

  /**
   * Get time until video call is available
   *
   * Calculates how many minutes until the video call can be joined.
   * Returns 0 if the call can be joined now.
   * Returns negative value if the appointment time has passed.
   *
   * @param scheduledStartAt - Appointment start time (ISO string)
   * @returns Minutes until call is available (negative if past)
   *
   * @example
   * ```typescript
   * const minutesUntil = videoService.getMinutesUntilAvailable(
   *   appointment.scheduled_start_at
   * );
   *
   * if (minutesUntil > 15) {
   *   console.log(`Video call available in ${minutesUntil} minutes`);
   * } else if (minutesUntil > 0) {
   *   console.log("Video call available soon");
   * } else {
   *   console.log("Video call available now");
   * }
   * ```
   */
  getMinutesUntilAvailable(scheduledStartAt: string): number {
    const startTime = new Date(scheduledStartAt);
    const now = new Date();
    const fifteenMinutes = 15 * 60 * 1000;

    // Calculate time difference
    const timeDiff = startTime.getTime() - now.getTime() - fifteenMinutes;

    // Convert to minutes
    return Math.ceil(timeDiff / (60 * 1000));
  }

  /**
   * Validate Google Meet link format
   *
   * Checks if a URL is a valid Google Meet link.
   *
   * @param url - URL to validate
   * @returns true if valid Google Meet link, false otherwise
   *
   * @example
   * ```typescript
   * videoService.validateMeetLink("https://meet.google.com/abc-defg-hij"); // true
   * videoService.validateMeetLink("https://zoom.us/j/123456"); // false
   * videoService.validateMeetLink("invalid"); // false
   * ```
   */
  validateMeetLink(url: string): boolean {
    try {
      const parsedUrl = new URL(url);
      return (
        parsedUrl.hostname === "meet.google.com" &&
        parsedUrl.pathname.length > 1
      );
    } catch (error) {
      return false;
    }
  }

  /**
   * Copy video link to clipboard
   *
   * Copies a Google Meet link to the system clipboard.
   * Useful for sharing the link with others.
   *
   * @param meetLink - Google Meet URL
   * @returns Promise that resolves when link is copied
   *
   * @example
   * ```typescript
   * const handleCopyLink = async () => {
   *   try {
   *     await videoService.copyLinkToClipboard(videoLink.meet_link);
   *     toast.success("Link copied to clipboard!");
   *   } catch (error) {
   *     toast.error("Failed to copy link");
   *   }
   * };
   * ```
   */
  async copyLinkToClipboard(meetLink: string): Promise<void> {
    try {
      await navigator.clipboard.writeText(meetLink);
      console.log("Video link copied to clipboard");
    } catch (error) {
      console.error("Failed to copy link to clipboard:", error);
      throw new Error("Failed to copy link to clipboard");
    }
  }
}

/**
 * Export singleton instance of VideoService
 *
 * Use this instance throughout the application for video consultation operations.
 * Do not create new instances of VideoService.
 *
 * @example
 * ```typescript
 * import videoService from './services/videoService';
 *
 * // Get video link
 * const videoLink = await videoService.getVideoLink(appointmentId);
 *
 * // Open video link
 * videoService.openVideoLink(videoLink.meet_link);
 *
 * // Check if video call is available
 * if (videoService.isVideoCallAvailable(appointment)) {
 *   // Show join button
 * }
 *
 * // Get time until available
 * const minutes = videoService.getMinutesUntilAvailable(
 *   appointment.scheduled_start_at
 * );
 *
 * // Copy link to clipboard
 * await videoService.copyLinkToClipboard(videoLink.meet_link);
 * ```
 */
export default new VideoService();
